import { Box } from '@mui/material'
import React from 'react'

const about = () => {
  return (
    <Box>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea sequi quasi mollitia eos dolor quas reprehenderit alias inventore omnis eveniet voluptate obcaecati similique nostrum error quo cupiditate, delectus corporis minima fugit! Cumque officia voluptas perferendis recusandae eius dignissimos sequi eveniet veniam, dicta, earum accusantium non, consectetur reiciendis magnam libero repellat rerum illo! Et corporis aliquam quas ut hic deleniti doloremque, pariatur quasi! Cupiditate minus itaque illum a sunt atque tenetur ipsum eius, eligendi et officiis corrupti porro necessitatibus, libero, quaerat eaque rem fuga iste. Deserunt eum laboriosam quod omnis error ullam et tempore itaque harum nihil, impedit nostrum, modi ea sit quae quidem explicabo. Mollitia delectus molestias aliquid tempora officia omnis facilis maiores possimus vel ab quaerat distinctio nihil odit harum vitae, amet alias quas voluptatibus unde earum quibusdam, fugit explicabo. Nesciunt illum neque quisquam, tempora, veritatis eaque provident quam magni numquam magnam reiciendis amet. Repellendus rem repudiandae nulla ea quos impedit beatae exercitationem asperiores quasi, rerum omnis praesentium ipsum voluptatem, pariatur dicta, voluptas provident aperiam corrupti dolore aliquam. Nam, unde mollitia! Omnis nostrum ab fuga, deleniti quam ad non! Natus pariatur tenetur, officia repudiandae ullam earum animi quia voluptate. Ipsa blanditiis illum molestias quidem, incidunt sunt! Voluptates odio sapiente suscipit fuga consectetur minus! Fugit eos hic magnam non ad neque quam dignissimos nesciunt, libero eius eum adipisci laudantium expedita vero delectus corrupti id omnis perferendis rem dolor porro fugiat. Cumque molestias, porro veniam vel vitae soluta laboriosam ratione et maxime praesentium ipsam? Nesciunt eligendi fugiat, debitis doloribus in iste sed repellendus ipsum, assumenda, possimus molestias eaque inventore aperiam? Sint voluptate facere aspernatur quasi alias nisi optio voluptatem minus id harum reprehenderit, rerum totam dolore nobis error vitae excepturi adipisci, soluta illo ex dolor consequatur molestiae magni! Earum ex doloremque eaque, corrupti dolor quos quibusdam deserunt minus illum harum aliquid voluptatum, provident placeat nemo, adipisci cupiditate amet! Molestiae qui, quas quidem voluptatibus in quod. Incidunt rerum aperiam deleniti. Magni perspiciatis officia sed harum labore exercitationem beatae, minima distinctio facere. Repellat aut perferendis dolorem, quam ex non magnam illo veritatis delectus earum assumenda voluptate alias, error laborum vitae quae. Facere hic nam earum odio cum ex dicta libero quam fuga alias est repudiandae debitis cupiditate, odit unde maiores nobis labore repellendus officiis eius numquam voluptatibus! Sequi nesciunt velit neque reiciendis maxime illo assumenda in tempore quae. Repellat at fugiat repudiandae libero, dolore deleniti porro harum doloribus numquam rem fugit cum perspiciatis!
    </Box>
  )
}

export default about